.TH SX 1 "25 August 2018"
.SH NAME
sx \- start an xorg server
.SH SYNOPSIS
.B sx
.RI [ "command " [ "arguments " ...]]
.SH DESCRIPTION
.B sx
can be used to replace both
.BR xinit (1)
and
.BR startx (1)
for starting an Xorg server.  By default
.B sx
will attempt execute
.I sxrc
unless a
.I command
argument is provided.  The
.I command
may consistent of one or more
.IR arguments .
.SH ENVIRONMENT
.TP
.B XAUTHORITY
This environment references a file which stores authorisation entries
used to secure
.BR Xorg (1) .
If this environment is not set then
.B sx
will create and use
.B \%XDG_DATA_HOME/sx/xauthority
instead while also exporting this value to
.BR XAUTHORITY .
.TP
.B XDG_CONFIG_HOME
The directory used when searching for
.IR sxrc .
.B \%HOME/.config
will be used if not set.
.TP
.B XDG_DATA_HOME
The directory used for storing the
.I xauthority
file.
.B \%HOME/.local/share
will be used if not set.
.SH FILES
.TP
.B XDG_CONFIG_HOME/sx/sxrc
The default command started by
.BR sx .
This file must be executable.
.TP
.B XDG_DATA_HOME/sx/xauthority
The default authority used by
.B sx
if an alternative file is not provided with
.BR XAUTHORITY .
.SH NOTES
Since the addition of
.BR Xorg.wrap (1)
it may be necessary to set
.I allowed_users
to
.I anybody
in
.BR \%/etc/X11/Xwrapper.config .
This is due to
.B sx
attempting to run commands from within a subshell and is thusly not considered
a console user.
.SH SOURCE
.UR https://github.com/Earnestly/sx
.UE
.SH SEE ALSO
.BR Xorg (1),
.BR xinit (1),
.BR startx (1),
.BR Xsecurity (7),
.BR X (7)
