.TH sx 1 2017-05-12 sx

.SH NAME
sx \- start an xserver

.SH SYNOPSIS
.B sx
.RI [ client ]

.SH DESCRIPTION
.B sx
can be used to replace both
.BR xinit (1)
and
.BR startx (1)
for starting an Xorg server.  By default
.B sx
will attempt execute
.I sxrc
unless a
.I client
argument is provided.

.SH ENVIRONMENT
.TP
.B XAUTHORITY
This environment references a file which stores authorisation entries
used to secure
.BR Xorg (1) .
If this environment is not set then
.B sx
will create and use
.IR \%$XDG_CONFIG_HOME/sx/xauthority
instead while also exporting this value to
.BR XAUTHORITY .

.SH FILES
.TP
.BR $XDG_CONFIG_HOME/sx/sxrc " " "" ( $HOME/.config/sx/sxrc )
The default client started by
.BR sx .
This file must be executable.
.TP
.BR $XDG_CONFIG_HOME/sx/xauthority " " "" ( $HOME/.config/sx/xauthority )
The default authority used by
.B sx
if an alternative file is not provided with
.BR $XAUTHORITY .

.SH SOURCE
.UR https://github.com/Earnestly/sx
.UE

.SH SEE ALSO
.BR xinit (1),
.BR startx (1),
.BR Xserver (1),
.BR Xsecurity (7),
.BR X (7)
